### ISSUE TITLE
Transitive referanser gir kræsj på dotnet 8

### ISSUE THREAD

**Issue by roar-andersen** [folkehelseinstituttet/fhi.helseid#317]
Får følgende kræsj på grunn av versjonskonflikt mellom transitive referanser. Skjer i prosjekter hvor andre refererte pakker har transitiv referanse til nyere versjon av Microsoft.IdentityModel.Tokens. Ulike versjoner av Microsoft.IdentityModel.Protocols.OpenIdConnect og Microsoft.IdentityModel.Tokens forårsaker kræsjen. Kan løses ved å eksplisitt legge inn referanse til ny versjon av Microsoft.IdentityModel.Protocols.OpenIdConnect, men direkte støtte for dotnet 8 hadde vært å foretrekke.,

Har laget en PR  (#316) slik at både dotnet 6 og 8 støttes direkte, men støtte for dotnet 8 påvirker også workflow filene og jeg er usikker på om det er blitt løst riktig.

```
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII of type 'System.String' is hidden. For more details, see https://aka.ms/IdentityModel/PII.]'.
 ---> System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.Json.JsonConvert' from assembly 'Microsoft.IdentityModel.Tokens, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.GetAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.Microsoft.IdentityModel.Protocols.IConfigurationRetriever<Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfiguration>.GetConfigurationAsync(String address, IDocumentRetriever retriever, CancellationToken cancel)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.HandleAuthenticateAsync()


```

**Comment by OsirisTerje** [comment]
Det ser riktig ut for meg.
